# -*- coding: utf-8 -*-
"""Untitled48.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TurRfIESy7dLSTNUzkDnExie5ceGxV01
"""

import pandas as pd
 baza={
     "FISH":[ "Qadamova Zulayho",  "Qadamov Otabek", "Zokirova Zarina"   ],
     "Yoshi":[ "28" , "31"  , '42' ],
     'Manzili':[ "Farg'ona shaxar"  , "Andijon shaxar" , "Andijon viloyati"  ],
     "Jinsi":[ 'ayol' , 'erkak'  ,'ayol' ],
     "Ish joyi":[ 'TATUFF'  , "FVFVV", "FARDU" ]

 }
 db=pd.DataFrame(baza)
 print(db)

filtr=db[db['Jinsi']=='ayol']
print(filtr)

filtr=db[(db['Jinsi']=='ayol') & (db['Ish joyi']=='TATUFF') & (db['Yoshi']>'25')]
print(filtr)